### ISSUE TITLE
When sending a message to a group, TellBot doesn't recognize the sender when they're using an alias

### ISSUE THREAD

**Issue by EuphoricCatface** [CylonicRaider/tellbot#3]
**Description:** 
When you send a message as an alias to a group in which you're included, the bot doesn't realize that it was you that sent the message. i.e. you get to receive the message you sent, even though you're the sender.

**How to reproduce:**
Send a message as '응즞응' to *ITG via 'TellBot', and then post any message on euph, either as '응즞응' or 'ㅇㅈㅇ'

**Expected behavior:**
I don't receive my message, as I am the sender

**What actually happens:**
I do receive my message

**Examples:**
Timestamped at around 07:00 UTC in &xkcd
```
[응즞응] !tell *ITG I got 2x nvidia electronics designers' rulers! https://i.imgur.com/xF0nNkrh.jpg
  [TellBot] Will tell *ITG (PouncySilverkitten, Nuvanda, totally𝗁𝗎𝗆𝖺𝗇, DoctorNumberFour, Xyzzy, ㅇㅈㅇ, K, Garmy, A, Tomsci, and liff).
  [응즞응] .
    [TellBot] [You to *ITG, 6s ago] I got 2x nvidia electronics designers' rulers! https://i.imgur.com/xF0nNkrh.jpg
```

Timestamped at around 08:20 UTC in &test
```
[ㅇㅈㅇ] !tgroup *test @ㅇㅈㅇ @abc
  [TellBot] Group: *test
            Members before: -none-
            Members after (2): you and abc
[응즞응] !tell *test test
  [TellBot] Will tell *test (ㅇㅈㅇ and abc).
[ㅇㅈㅇ] ㅁ
  [TellBot] [응즞응 to *test, 8s ago] test
[ㅇㅈㅇ] !tell *test test
  [TellBot] Will tell *test (abc and ...).
[ㅇㅈㅇ] a
[abc] a
  [TellBot] [응즞응 to *test, 57s ago] test
  [TellBot] [ㅇㅈㅇ to *test, 41s ago] test
```

**Comment by CylonicRaider** [comment]
Ooh, someone filed a formal issue about that! \*actually starts fixing\*
